apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: connect2azopenai
  annotations:
    github.com/project-slug: DataAIDevOps/connect2azopenai
spec:
  type: other
  lifecycle: unknown
  owner: msmanufacturingcsu/teama
